import { MessageCircle } from "lucide-react";
import { siteConfig } from "@/data/site";

export function Booking() {
  return <section id="reservar" className="section-space bg-[#f6f3ec]"><div className="container-site">
    <div className="mx-auto max-w-4xl text-center"><p className="eyebrow mb-5 text-[#5e8490]">Sua próxima pausa</p><h2 className="font-display text-[clamp(3.4rem,9vw,7.5rem)] leading-[.86] tracking-[-.055em]">Escolha onde<br /><em className="font-normal">reservar.</em></h2><p className="mx-auto mt-7 max-w-xl text-lg text-[#49625d]">Consulte as datas disponíveis na plataforma de sua preferência ou fale diretamente conosco.</p></div>
    <div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-2"><a href={siteConfig.bookingUrl} target="_blank" rel="noopener noreferrer" className="group border border-[#163c35]/25 bg-[#fffdf8] p-7 transition-colors hover:bg-[#163c35] hover:text-[#f6f3ec] md:p-9"><span className="eyebrow text-[#5e8490] group-hover:text-[#8ea596]">Booking.com</span><h3 className="font-display mt-8 text-3xl">Reservar pelo Booking</h3><p className="mt-3 text-sm opacity-70">Ver disponibilidade, valores e condições.</p></a><a href={siteConfig.airbnbUrl} target="_blank" rel="noopener noreferrer" className="group border border-[#163c35]/25 bg-[#fffdf8] p-7 transition-colors hover:bg-[#163c35] hover:text-[#f6f3ec] md:p-9"><span className="eyebrow text-[#5e8490] group-hover:text-[#8ea596]">Airbnb</span><h3 className="font-display mt-8 text-3xl">Reservar pelo Airbnb</h3><p className="mt-3 text-sm opacity-70">Conhecer o anúncio e conferir suas datas.</p></a></div>
    <div className="mx-auto mt-5 max-w-5xl bg-[#d8c8ae] p-7 text-center md:flex md:items-center md:justify-between md:text-left"><div><p className="font-display text-2xl">Prefere conversar primeiro?</p><p className="mt-1 text-sm text-[#49625d]">Escreva para a Casa da Lagoa e tire suas dúvidas.</p></div><a href={siteConfig.whatsappUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center justify-center gap-2 bg-[#163c35] px-6 py-3.5 text-sm font-bold text-[#f6f3ec] md:mt-0"><MessageCircle className="size-4" aria-hidden="true" />Falar pelo WhatsApp</a></div>
  </div></section>;
}
